export const CATEGORIES = 'CATEGORIES';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const SUPPLIERS = 'SUPPLIERS';
export const SUPPLIERS_SUCCESS = 'SUPPLIERS_SUCCESS';
export const SUPPLIERS_FAIL = 'SUPPLIERS_FAIL';

export const SPARE_PARTS = 'SPARE_PARTS';
export const SPARE_PARTS_SUCCESS = 'SPARE_PARTS_SUCCESS';
export const SPARE_PARTS_FAIL = 'SPARE_PARTS_FAIL';


export const MECHANICS = 'MECHANICS';
export const MECHANICS_SUCCESS = 'MECHANICS_SUCCESS';
export const MECHANICS_FAIL = 'MECHANICS_FAIL';

export const ONLINE = 'ONLINE';
export const ONLINE_SUCCESS = 'ONLINE_SUCCESS';
export const ONLINE_FAIL = 'ONLINE_FAIL';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';