export const validationStings = {
  songsText: 'SONGS',
  artistName: 'Artist Name: ',
  loadingText: 'Please wait while we process your request',
  songDetail: 'TRACK DETAIL',
  length:'Length: ',
  easyMech:'EasyMech2U',
  loginContinue:'Please login to continue',
  forgotPasswordLogin:'Forgot Password?',
  login:'Login',
  signup:' Sign Up',
  dontAc:'Don’t Have an Account?',
  resetPassword:'It\'s Okay Reset Your Password',
  enterEmail:'Please enter your email to receive the verification code',
  next:'Next',
  forgotPassword:'Forgot Password',
  verifyOtp:'Verify OTP',
  enterVerifyCode:'Enter the 4 digits OTP via SMS on your phone number ',
  receiveCode:'If you don\'t receive code ?',
  resendNow:' Resend Now',
  verify:'Verify',
  resetYour:'Reset Your Password',
  newPasswordDiff:'New password must be diffrent from previous password',
  congratulation:'Congratulations',
  registerSuccess:'Registered Successfully',
  gotoLogin:'Go To Login',
  whoo:'Whoo Whoo !!',
  resetSuccess:'Your password has been reset successfully \n Now login with your new password. ',
  createAc:'Create an account',
  camera:'Camera',
  gallery:'Gallery',
  searchAddress:'Search Address',
  searchLocation:'Search Location...',
  gotToLogin:'Go To Login',
  homeText:'Home',
  logoutText:'Logout',
  logoutDescText:'Are you sure you want to logout ?',
  okText:'Ok',
  cancelText:'Cancel',
  deleteAcText:'Delete Account',
  deleteDescText:'Are you sure you want to delete account ?',
  profileText:'Profile',
  deleteAccount:'Delete Account',
  logoutText:'Logout',
  profileText:'Profile',
  changePassword:'Change Password',
  editProfile:'Edit Profile',
  updateText:'Update',
  searchCategory:'Search Category',
  supplier:'Supplier',
  sparepart:'Spare Parts',
  callNumberText:'You have to call on this',
  invalidOtp:'Please enter correct OTP',
  dashboardText:'Dashboard',
  submitText:'Submit',
  adminApproval:'Waiting for admin\'s approval.Once it will be approval you can login.',
  terms:'Please indicate that you have read and agree to the',
  conditions:' Terms and Conditions.',
  updateService:'Update Services',
  //Placeholder Text

  emailPlaceholder:'Email',
  passwordPlaceholder:'Password',
  newPasswordPlaceHolder:'New Password',
  resetPasswordHeader:'Reset Password',
  confirmPasswordPlaceHolder:'Confirm Password',
  fullNamePlaceholder:'Full Name',
  phoneNumberPlaceholder:'Phone Number',
  locationPlaceHolder:'Location',
  dobPlaceholder:'Date of Birth',
  oldPasswordPlaceholder:'Old Password',
  newPasswordPlaceholder:'New Password',
  updateLicensePlaceholder:'Update License Doc',
  serviceCharges:'Service fee will be ₦5 for each category',
  connectingText:'Thank you for connected with us !!',
  termsTitle:'Terms and conditions',
  selectCategory:'Select Category',
  //Validation error

  nameError:'Name is required',
  emailError:'Email is required',
  phoneNumberError:'Phone number is required',
  passwordError:'Password is required',
  confirmPasswordError:'Confirm password is required',
  passwordLengthError:'Password should be of atmost 8 characters.',
  passwordMismatchError:'Password doesn\'t match',
  locationError:'Location is required',
  dobError:'Date of birth is required',
  profileImageError:'Profile picture is required',
  licenseImageError:'License picture is required',
  selectServiceError:'Services is required',
  oldPasswordvalid:'Old password is required',
  newPasswordvalid:'New password is required',
  otpvalid:'4 digits otp is required',
  termsValid:'Please terms and conditions.'


};
