export const images = {
  icToggleOn: require('../../assets/images/onButton.png'),
  icToggleOff: require('../../assets/images/offButton.png'),
  icBack: require('../../assets/images/back.png'),
  icGrowth: require('../../assets/images/growth.png'),
  icSettings: require('../../assets/images/settings.png'),
  icArrow: require('../../assets/images/arrow.png'),
  icEmail:require('../../assets/images/mail.png'),
  icPassword:require('../../assets/images/password.png'),
  icUser:require('../../assets/images/user.png'),
  icLock:require('../../assets/images/lock.png'),
  icLogo:require('../../assets/images/logo.png'),
  icSwitch:require('../../assets/images/switch.png'),
  icdob:require('../../assets/images/dob.png'),
  icFacebook:require('../../assets/images/facebook.png'),
  icGoogle:require('../../assets/images/google.png'),
  icApple:require('../../assets/images/apple.png'),
  icForgotPassword:require('../../assets/images/forgot-password.png'),
  icResetPassword:require('../../assets/images/resetpassword.png'),
  icCamera:require('../../assets/images/camera.png'),
  icMan:require('../../assets/images/profile.png'),
  icNavigation:require('../../assets/images/navigation.png'),
  icCam:require('../../assets/images/cam.png'),
  icGallery:require('../../assets/images/gallery.png'),
  icRemove:require('../../assets/images/remove.png'),
  icSearch:require('../../assets/images/search.png'),
  icDelete:require('../../assets/images/delete.png'),
  icLogout:require('../../assets/images/logout.png'),
  icHome:require('../../assets/images/home.png'),
  icMenu:require('../../assets/images/menu.png'),
  icPhone:require('../../assets/images/telephone.png'),
  icEdit:require('../../assets/images/edit.png'),
  icResetPass:require('../../assets/images/reset-password.png'),
  icEmoji:require('../../assets/images/emoji.png'),
  icNav:require('../../assets/images/navWhite.png'),
  icRegister:require('../../assets/images/register.png'),
  icFile:require('../../assets/images/file.png'),
  icVerified:require('../../assets/images/verified.png'),
  icOnline:require('../../assets/images/online.png'),
  icOffline:require('../../assets/images/offline.png'),
  icPositive:require('../../assets/images/positive.png'),
  icCheck:require('../../assets/images/check.png'),
  icUncheck:require('../../assets/images/uncheck.png'),
  icCategory:require('../../assets/images/category.png'),
  icLicense:require('../../assets/images/license.png'),
  icAboutus:require('../../assets/images/info.png'),
  icHide:require('../../assets/images/hide.png'),
  icShow:require('../../assets/images/show.png'),
  icContact:require('../../assets/images/contact.png'),

};
